### Day20 - RAGAS Evaluation

In [5]:
# Uncomment if needed

# !pip install ragas
# !pip install datasets
# !pip install langchain-groq
# !pip install litellm

FILE_NAME = 'SAMPLE_RAG_Ground_Truth_Eval'

In [2]:
import json
import pandas as pd

from datasets import Dataset
from langchain_huggingface import HuggingFaceEmbeddings

from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall
)

from langchain_groq import ChatGroq

In [9]:
# INPUT_JSON = "data/Test_Questions_Eval.json"
INPUT_JSON = "./data/%s.json" % FILE_NAME

with open(INPUT_JSON, "r", encoding="utf-8") as f:
    data = json.load(f)

print(f"Loaded {len(data)} evaluation samples")

Loaded 39 evaluation samples

In [10]:
df = pd.DataFrame(data)
display(df)

,answer,context,question,expected_source,ground_truth_answer
0,The probation period for new full-time employe...,[Employees may be classified into the followin...,What is the probation period for new full-time...,employee_handbook,All new Full-Time employees undergo a standard...
1,I couldn't find this information in the policies.,[Economy class is standard. Business class req...,What are the standard office hours?,employee_handbook,"Monday to Friday, 9:00 AM–6:00 PM (IST)."
2,"According to the context, eligible employees m...","[Standard office hours are Monday to Friday, 9...",How many days per week can eligible employees ...,employee_handbook,Up to three days per week with manager approval.
3,VPN must be used whenever accessing corporate ...,[used whenever accessing corporate resources f...,Is VPN required for remote access?,employee_handbook,Yes. Company-approved corporate VPN is mandato...
4,"According to the context, full-time employees ...",[tems remotely.\n4 Time Off and Leave Policy\n...,How many annual leave days do full-time employ...,employee_handbook,18 days.
5,"According to the context, ""Medical Leave: 10 d...",[tems remotely.\n4 Time Off and Leave Policy\n...,How many medical leave days are provided?,employee_handbook,10 days.
6,I couldn't find this information in the policies.,[3.1 Working Hours . . . . . . . . . . . . . ....,How often are performance reviews conducted?,employee_handbook,"Twice yearly, in June and December."
7,I couldn't find this information in the policies.,[3.1 Working Hours . . . . . . . . . . . . . ....,What is the annual learning budget?,employee_handbook,"$1,500 (or local equivalent)."
8,I couldn't find this information in the policies.,[up to termination. Violations may result in c...,How often must passwords be rotated?,employee_handbook,Every 90 days.
9,I couldn't find this information in the policies.,[up to termination. Violations may result in c...,What is the resignation notice period?,employee_handbook,30 days for full-time employees.
10,NaN,NaN,NaN,it_security_policy,Passwords must contain at least 12 characters ...
11,NaN,NaN,NaN,it_security_policy,No. Password sharing is prohibited.
12,NaN,NaN,NaN,it_security_policy,"Yes, for all corporate accounts."
13,NaN,NaN,NaN,it_security_policy,Whenever accessing corporate resources from ou...
14,NaN,NaN,NaN,it_security_policy,Report the lost device within one hour.
15,NaN,NaN,NaN,it_security_policy,No. Unauthorized USB storage devices are block...
16,NaN,NaN,NaN,it_security_policy,Do not open suspicious attachments or click un...
17,NaN,NaN,NaN,it_security_policy,To the Information Security team immediately.
18,NaN,NaN,NaN,code_of_conduct,"Harassment, discrimination and bullying are pr..."
19,"According to the context: \n\n""Employees must ...",[Employees must disclose any potential conflic...,What must employees disclose regarding conflic...,code_of_conduct,"Any potential conflicts involving customers, s..."
20,"According to the context: \n\n""Gifts above com...",[Gifts\nGifts above company thresholds require...,What is required for gifts above company thres...,code_of_conduct,Written approval.
21,"No, confidential company information must not ...",[not be disclosed to unauthorized persons. Con...,Can confidential company information be disclo...,code_of_conduct,No. It must not be disclosed to unauthorized p...
22,"According to the context: \n\n""No, Employees s...",[Employees should not represent personal opini...,Can employees present personal opinions as com...,code_of_conduct,No.
23,"According to the context: \n\n""Approved AI too...",[specifically authorized. Approved AI tools ma...,Can approved AI tools be used with confidentia...,code_of_conduct,Only if specifically authorized; otherwise onl...
24,"According to the context, employees may confid...",[ethical concerns without fear of retaliation....,How can employees report ethical concerns?,code_of_conduct,Confidentially and without fear of retaliation.
25,Violations may result in corrective action up ...,[up to termination. Violations may result in c...,What may happen if the code of conduct is viol...,code_of_conduct,Corrective action up to termination.
26,"According to the context: \n\n""Domestic travel...",[international business travel. This policy go...,Who must approve domestic travel?,travel_policy,Manager approval.
27,"According to the policy: ""International travel...",[international business travel. This policy go...,Who must approve international travel?,travel_policy,Vice President approval.
28,I couldn't find this information in the policies.,[reimbursement is permitted for airport transf...,What class of air travel is standard?,travel_policy,Economy class.
29,NaN,NaN,NaN,travel_policy,With executive approval for flights over eight...
30,NaN,NaN,NaN,travel_policy,Capped at published city limits unless pre-app...
31,NaN,NaN,NaN,travel_policy,According to travel location.
32,NaN,NaN,NaN,travel_policy,For airport transfers and official meetings wi...
33,NaN,NaN,NaN,travel_policy,Within 30 days after travel with supporting re...
34,NaN,NaN,NaN,travel_policy,Corporate card usage is encouraged; currency c...
35,NaN,NaN,NaN,cross_document,No. Unauthorized USB storage devices are block...
36,NaN,NaN,NaN,cross_document,Use the corporate VPN for remote access; VPN i...
37,NaN,NaN,NaN,cross_document,"No, unless specifically authorized. Approved A..."
38,"""I couldn't find this information in the polic...",[not be disclosed to unauthorized persons. Con...,What happens if I share confidential company d...,cross_document,It violates the code of conduct and may lead t...

In [11]:
ragas_rows = []

for row in data:
    # print("question" in row.keys())
    if "question" in row.keys():
        ragas_rows.append({
            "question": row["question"],
            "answer": row["answer"],
            "contexts": row["context"],
            "ground_truth": row["ground_truth_answer"]
        })

dataset = Dataset.from_list(ragas_rows)

display(dataset)

Dataset({
    features: ['question', 'answer', 'contexts', 'ground_truth'],
    num_rows: 21
})

In [6]:
# import os
# from dotenv import load_dotenv
# # 1. Load the environment variables from your .env file
# loaded = load_dotenv()
# if not loaded:
#     raise ValueError("No keys found! Please check your .env file.")
#
# env = open('./.env', 'r')
# #print(env.read())
# print(os.getenv('GROQ_API_KEY2'))
#
# # Verify the key is loaded (don't print the actual key in output!)
# # if not os.getenv("GROQ_API_KEY"):
# #     raise ValueError("GROQ_API_KEY not found. Please check your .env file.")
#
# judge_llm = ChatGroq(
#     model="llama-3.1-70b-versatile",
#     temperature=0
# )

In [12]:
import os
from dotenv import load_dotenv

# 1. Load the environment variables from your .env file
load_dotenv(override=True)

# Verify the key is loaded (don't print the actual key in output!)
if not os.getenv("GROQ_API_KEY"):
    raise ValueError("GROQ_API_KEY not found. Please check your .env file.")

# 2. Initialize Models
# Requires GROQ_API_KEY in your .env file
judge_model = ChatGroq(
    # CHECK: https://console.groq.com/docs/deprecations
    # model="llama-3.1-8b-instant",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=4096
)

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print(f"✅ Judge LLM configured as: {judge_model.model_name}")
print(f"✅ Embeddings configured as: {embeddings.model_name}")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

✅ Judge LLM configured as: llama-3.3-70b-versatile
✅ Embeddings configured as: sentence-transformers/all-MiniLM-L6-v2

In [13]:
# Execute Ragas using the cloud models
score = evaluate(
    dataset=dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_precision,
        context_recall
    ],
    llm=judge_model,
    embeddings=embeddings,
    # Prevents the entire run from failing if one evaluation errors out
    raise_exceptions=False,
    # Prevents overload
    batch_size=4
)

# Output as a clean Pandas DataFrame for analysis
results_df = score.to_pandas()
display(pd.DataFrame(results_df))
print()

Evaluating:   0%|          | 0/84 [00:00<?, ?it/s]

Batch 1/21:   0%|          | 0/4 [00:00<?, ?it/s]

Exception raised in Job[42]: TimeoutError()
Exception raised in Job[47]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99800, Requested 1247. Please try again in 15m4.608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[45]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99764, Requested 539. Please try again in 4m21.792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[44]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99752, Requested 549. Please try again in 4m20.064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[46]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99748, Requested 1149. Please try again in 12m55.008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[49]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99627, Requested 557. Please try again in 2m38.976s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[50]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99623, Requested 5090. Please try again in 1h7m52.031999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[51]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99612, Requested 1254. Please try again in 12m28.223999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[48]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99612, Requested 566. Please try again in 2m33.792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[55]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99515, Requested 5183. Please try again in 1h7m39.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[54]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99506, Requested 1138. Please try again in 9m16.416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[53]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99476, Requested 4482. Please try again in 56m59.711999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[52]: TimeoutError()
Exception raised in Job[57]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99315, Requested 4527. Please try again in 55m19.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[58]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99301, Requested 5101. Please try again in 1h3m23.327999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[59]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99270, Requested 5214. Please try again in 1h4m34.176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[56]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99269, Requested 4539. Please try again in 54m50.112s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[63]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99197, Requested 5218. Please try again in 1h3m34.56s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[62]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99177, Requested 5093. Please try again in 1h1m29.28s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[60]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99168, Requested 4549. Please try again in 53m31.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[61]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99130, Requested 4540. Please try again in 52m50.88s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[65]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99001, Requested 4470. Please try again in 49m58.944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[66]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99000, Requested 5032. Please try again in 58m3.648s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[64]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98997, Requested 4483. Please try again in 50m6.72s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[67]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98977, Requested 5159. Please try again in 59m33.504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[69]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98886, Requested 4487. Please try again in 48m34.272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[68]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98882, Requested 4495. Please try again in 48m37.728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[71]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98858, Requested 5184. Please try again in 58m12.288s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[70]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98848, Requested 5082. Please try again in 56m35.52s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[73]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98769, Requested 4485. Please try again in 46m51.456s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[75]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98746, Requested 5186. Please try again in 56m37.248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[72]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98724, Requested 4493. Please try again in 46m19.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[74]: TimeoutError()
Exception raised in Job[78]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98514, Requested 5091. Please try again in 51m54.72s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[77]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98484, Requested 4469. Please try again in 42m31.392s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[76]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98474, Requested 4479. Please try again in 42m31.392s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[79]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98443, Requested 5156. Please try again in 51m49.536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[81]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98352, Requested 4470. Please try again in 40m38.208s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[83]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98349, Requested 5204. Please try again in 51m9.792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[82]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98339, Requested 5099. Please try again in 49m30.432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})
Exception raised in Job[80]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvmqhvbte61vev1wapfyx37n` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98307, Requested 4483. Please try again in 40m10.56s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}})

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,What is the probation period for new full-time...,[Employees may be classified into the followin...,The probation period for new full-time employe...,All new Full-Time employees undergo a standard...,1.0,1.000000,1.0,1.0
1,What are the standard office hours?,[Economy class is standard. Business class req...,I couldn't find this information in the policies.,"Monday to Friday, 9:00 AM–6:00 PM (IST).",1.0,0.000000,0.0,0.0
2,How many days per week can eligible employees ...,"[Standard office hours are Monday to Friday, 9...","According to the context, eligible employees m...",Up to three days per week with manager approval.,1.0,0.884653,1.0,1.0
3,Is VPN required for remote access?,[used whenever accessing corporate resources f...,VPN must be used whenever accessing corporate ...,Yes. Company-approved corporate VPN is mandato...,1.0,0.855592,1.0,1.0
4,How many annual leave days do full-time employ...,[tems remotely.\n4 Time Off and Leave Policy\n...,"According to the context, full-time employees ...",18 days.,1.0,0.983338,1.0,1.0
5,How many medical leave days are provided?,[tems remotely.\n4 Time Off and Leave Policy\n...,"According to the context, ""Medical Leave: 10 d...",10 days.,1.0,0.931676,1.0,1.0
6,How often are performance reviews conducted?,[3.1 Working Hours . . . . . . . . . . . . . ....,I couldn't find this information in the policies.,"Twice yearly, in June and December.",1.0,0.000000,0.0,0.0
7,What is the annual learning budget?,[3.1 Working Hours . . . . . . . . . . . . . ....,I couldn't find this information in the policies.,"$1,500 (or local equivalent).",1.0,0.000000,0.0,0.0
8,How often must passwords be rotated?,[up to termination. Violations may result in c...,I couldn't find this information in the policies.,Every 90 days.,0.0,0.000000,0.0,0.0
9,What is the resignation notice period?,[up to termination. Violations may result in c...,I couldn't find this information in the policies.,30 days for full-time employees.,1.0,0.000000,0.0,0.0
10,What must employees disclose regarding conflic...,[Employees must disclose any potential conflic...,"According to the context: \n\n""Employees must ...","Any potential conflicts involving customers, s...",1.0,0.638461,NaN,1.0
11,What is required for gifts above company thres...,[Gifts\nGifts above company thresholds require...,"According to the context: \n\n""Gifts above com...",Written approval.,NaN,NaN,NaN,NaN
12,Can confidential company information be disclo...,[not be disclosed to unauthorized persons. Con...,"No, confidential company information must not ...",No. It must not be disclosed to unauthorized p...,NaN,NaN,NaN,NaN
13,Can employees present personal opinions as com...,[Employees should not represent personal opini...,"According to the context: \n\n""No, Employees s...",No.,NaN,NaN,NaN,NaN
14,Can approved AI tools be used with confidentia...,[specifically authorized. Approved AI tools ma...,"According to the context: \n\n""Approved AI too...",Only if specifically authorized; otherwise onl...,NaN,NaN,NaN,NaN
15,How can employees report ethical concerns?,[ethical concerns without fear of retaliation....,"According to the context, employees may confid...",Confidentially and without fear of retaliation.,NaN,NaN,NaN,NaN
16,What may happen if the code of conduct is viol...,[up to termination. Violations may result in c...,Violations may result in corrective action up ...,Corrective action up to termination.,NaN,NaN,NaN,NaN
17,Who must approve domestic travel?,[international business travel. This policy go...,"According to the context: \n\n""Domestic travel...",Manager approval.,NaN,NaN,NaN,NaN
18,Who must approve international travel?,[international business travel. This policy go...,"According to the policy: ""International travel...",Vice President approval.,NaN,NaN,NaN,NaN
19,What class of air travel is standard?,[reimbursement is permitted for airport transf...,I couldn't find this information in the policies.,Economy class.,NaN,NaN,NaN,NaN
20,What happens if I share confidential company d...,[not be disclosed to unauthorized persons. Con...,"""I couldn't find this information in the polic...",It violates the code of conduct and may lead t...,NaN,NaN,NaN,NaN

### ALTERNATE
#### OpenAI in lieu of Groq/HF

In [9]:
import os
import pandas as pd
from dotenv import load_dotenv

# Ensure you have imported the OpenAI equivalents from LangChain
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall
)

# 1. Load the environment variables from your .env file
load_dotenv(override=True)

# Verify the OpenAI key is loaded (don't print the actual key in output!)
if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY not found. Please check your .env file.")

# 2. Initialize Models
# Requires OPENAI_API_KEY in your .env file

# Using gpt-4o-mini as a fast, cost-effective judge model
judge_model = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    max_tokens=4096
)

# Using OpenAI's native embeddings
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

print(f"✅ Judge LLM configured as: {judge_model.model_name}")
print(f"✅ Embeddings configured as: {embeddings.model}")

✅ Judge LLM configured as: gpt-4o-mini
✅ Embeddings configured as: text-embedding-3-small

In [10]:
# 3. Execute Ragas using the OpenAI cloud models
# Assuming 'dataset' is defined prior to this snippet
score = evaluate(
    dataset=dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_precision,
        context_recall
    ],
    llm=judge_model,
    embeddings=embeddings,
    # Prevents the entire run from failing if one evaluation errors out
    raise_exceptions=False,
    # Prevents overload
    batch_size=4
)

# Output as a clean Pandas DataFrame for analysis
results_df = score.to_pandas()
display(pd.DataFrame(results_df))
print()

Evaluating:   0%|          | 0/84 [00:00<?, ?it/s]

Batch 1/21:   0%|          | 0/4 [00:00<?, ?it/s]

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,What is the probation period for new full-time...,[Employees may be classified into the followin...,The probation period for new full-time employe...,All new Full-Time employees undergo a standard...,1.0,1.000000,1.0,1.0
1,What are the standard office hours?,[Economy class is standard. Business class req...,I couldn't find this information in the policies.,"Monday to Friday, 9:00 AM–6:00 PM (IST).",1.0,0.000000,0.0,0.0
2,How many days per week can eligible employees ...,"[Standard office hours are Monday to Friday, 9...","According to the context, eligible employees m...",Up to three days per week with manager approval.,1.0,1.000000,1.0,1.0
3,Is VPN required for remote access?,[used whenever accessing corporate resources f...,VPN must be used whenever accessing corporate ...,Yes. Company-approved corporate VPN is mandato...,0.5,0.840783,1.0,1.0
4,How many annual leave days do full-time employ...,[tems remotely.\n4 Time Off and Leave Policy\n...,"According to the context, full-time employees ...",18 days.,1.0,0.936426,1.0,1.0
5,How many medical leave days are provided?,[tems remotely.\n4 Time Off and Leave Policy\n...,"According to the context, ""Medical Leave: 10 d...",10 days.,1.0,0.738983,1.0,1.0
6,How often are performance reviews conducted?,[3.1 Working Hours . . . . . . . . . . . . . ....,I couldn't find this information in the policies.,"Twice yearly, in June and December.",0.0,0.000000,0.0,0.0
7,What is the annual learning budget?,[3.1 Working Hours . . . . . . . . . . . . . ....,I couldn't find this information in the policies.,"$1,500 (or local equivalent).",0.0,0.000000,0.0,0.0
8,How often must passwords be rotated?,[up to termination. Violations may result in c...,I couldn't find this information in the policies.,Every 90 days.,0.0,0.000000,0.0,0.0
9,What is the resignation notice period?,[up to termination. Violations may result in c...,I couldn't find this information in the policies.,30 days for full-time employees.,0.0,0.000000,0.0,0.0
10,What must employees disclose regarding conflic...,[Employees must disclose any potential conflic...,"According to the context: \n\n""Employees must ...","Any potential conflicts involving customers, s...",1.0,0.942121,1.0,1.0
11,What is required for gifts above company thres...,[Gifts\nGifts above company thresholds require...,"According to the context: \n\n""Gifts above com...",Written approval.,1.0,1.000000,1.0,1.0
12,Can confidential company information be disclo...,[not be disclosed to unauthorized persons. Con...,"No, confidential company information must not ...",No. It must not be disclosed to unauthorized p...,1.0,0.802912,1.0,1.0
13,Can employees present personal opinions as com...,[Employees should not represent personal opini...,"According to the context: \n\n""No, Employees s...",No.,1.0,0.923326,1.0,0.0
14,Can approved AI tools be used with confidentia...,[specifically authorized. Approved AI tools ma...,"According to the context: \n\n""Approved AI too...",Only if specifically authorized; otherwise onl...,1.0,1.000000,1.0,1.0
15,How can employees report ethical concerns?,[ethical concerns without fear of retaliation....,"According to the context, employees may confid...",Confidentially and without fear of retaliation.,0.8,0.000000,1.0,1.0
16,What may happen if the code of conduct is viol...,[up to termination. Violations may result in c...,Violations may result in corrective action up ...,Corrective action up to termination.,1.0,0.000000,1.0,1.0
17,Who must approve domestic travel?,[international business travel. This policy go...,"According to the context: \n\n""Domestic travel...",Manager approval.,1.0,0.718882,1.0,1.0
18,Who must approve international travel?,[international business travel. This policy go...,"According to the policy: ""International travel...",Vice President approval.,1.0,0.640524,1.0,1.0
19,What class of air travel is standard?,[reimbursement is permitted for airport transf...,I couldn't find this information in the policies.,Economy class.,0.0,0.000000,0.0,0.0
20,What happens if I share confidential company d...,[not be disclosed to unauthorized persons. Con...,"""I couldn't find this information in the polic...",It violates the code of conduct and may lead t...,0.0,0.000000,1.0,0.0

In [17]:
import pandas as pd

# 1. Create a copy of the dataframe so we don't modify the original one in your notebook
export_df = results_df.copy()

# Note: Ragas typically names this column 'contexts', but we'll check for 'context' as well
target_col = 'contexts' if 'contexts' in export_df.columns else 'context'

# 2. Convert the list of strings into a single string separated by double newlines for readability
if target_col in export_df.columns:
    export_df[target_col] = export_df[target_col].apply(
        lambda x: "\n\n---\n\n".join(x) if isinstance(x, list) else x
    )

# 3. Save to Excel
excel_filename = "data/%s.xlsx" % FILE_NAME

# We use the openpyxl engine and set index=False so we don't get the arbitrary row numbers in the output
export_df.to_excel(excel_filename, index=False, engine='openpyxl')

print(f"✅ Results successfully formatted and saved to {excel_filename}")

✅ Results successfully formatted and saved to data/RAG_Ground_Truth_Eval.xlsx